### ISSUE TITLE
What's the benefit instead of running Wireguard in a Docker container?

### ISSUE THREAD

**Issue by thomasmerz** [amritb/poor-mans-vpn#2]
Why are you not using **Docker(-Compose)** instead of installing and setting up Wireguard?

Setting up a VM with Ansible is really great 👍🏻  but why do you not use a docker container? This would make your playbook much easier (install `docker` and `docker-compose`, copy `docker-compose.yml` and execute `docker-compose`)

For example:
https://github.com/linuxserver/docker-wireguard#usage
```
---
version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=wireguard.domain.com #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - /path/to/appdata/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```
